version: "3"

services:
  react-web:
    image: podster_react_web
    build:
      context: ./podster-react-web
      dockerfile: Dockerfile
    volumes:
      - ./podster-react-web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: on-failure
    stdin_open: true
    container_name: podster_react_web
